### ISSUE TITLE
Молодцы!

### ISSUE THREAD

**Issue by deniszagitov** [donatelloth/homebridge-neptun#1]
Ребята, если напишите плагин и документацию - я незамедлительно куплю нептуна)

**Comment by donatelloth** [comment]
Как только будет что тестировать - напишем. Пока можете следить здесь indahomekit.ru и в наших соц сетях.

**Comment by donatelloth** [comment]
Первая версия готова. Не забудьте использовать промо-код для NeptunSale.ru — INDAHOMEKIT — 15% скидка
